/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        Bookerly: ["Regular"],
        BookerlyItalic: ["Italic"],
        BookerlyBold: ["Bold"],
        BookerlyBoldItalic: ["BoldItalic"],
      },
      colors: {
        singular_1: "#BF8F00",
        singular_2: "#FFD765",
        plural_1: "#FFFF00",
        plural_2: "#FFFF9B",
        masculino_1: "#00B0F0",
        masculino_2: "#B7ECFF",
        femenino_1: "#FF66CC",
        femenino_2: "#FFBDE9",
        neutro_1: "#00FF00",
        neutro_2: "#9BFF9B",
        nominativo_1: "#1F3864",
        nominativo_2: "#B4C6E7",
        nominativo_3: "#D9E2F3",
        genitivo_1: "#FF3399",
        genitivo_2: "#FFBDDE",
        dativo_1: "#FF6600",
        dativo_2: "#FFCFAF",
        acusativo_1: "#7030A0",
        acusativo_2: "#9954CC",
        acusativo_3: "#D5B8EA",
        instrumental_1: "#FFC000",
        instrumental_2: "#FFEAA7",
        preposicional_1: "#00B050",
        preposicional_2: "#7DFFB8",
        verbos_1: "#C00000",
        verbos_2: "#FF8181",
        celeste_encabezado: "##5B9BD5",
        celeste_pregunta: "#00B0F0",
        imperfectivo_1: "#9900FF",
        imperfectivo_2: "#C46DFF",
        perfectivo_1: "#70309F",
        perfectivo_2: "#9F5FCF",
        perfectivo_imperfectivo: "#9966FF",
        frases_1: "#339933",
        frases_2: "#B0FF2F",
        frases_3: "#E4FFB7",
        frases_4: "#F2FFDD",
      },
    },
  },
  safelist: ["verbos_1"],
  plugins: [],
};
